### ISSUE TITLE
EFA-Configure add message size limit change

### ISSUE THREAD

**Issue by darky83** [E-F-A/v3#34]
by default postfix allows mails up to 10MB
we might want to add an section so users can change it to something else..

```
message_size_limit in postfix main.cf`*by default not set so default is used (10MB)
```

**Comment by pdwalker** [comment]
Just a note of caution:

I updated postfix today, and my message_size_limit was set to 42,949,672,960 (40GB).  This resulted in a rash of "452 4.3.1 Insufficient system storage" delivery errors from postfix because postfix expects a file system with 1.5x the message size in free space before it'll accept the message.

This feature should check to make sure the value chosen is not too large for the free file system space in order to prevent this soft error.
